BEGIN;
--
-- Create model Sale
--
CREATE TABLE "umag_hacknu_sale" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "barcode" bigint NOT NULL, "quantity" integer NOT NULL, "price" integer NOT NULL, "sale_time" timestamp with time zone NOT NULL);
--
-- Create model Supply
--
CREATE TABLE "umag_hacknu_supply" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "barcode" bigint NOT NULL, "quantity" integer NOT NULL, "price" integer NOT NULL, "supply_time" timestamp with time zone NOT NULL);
--
-- Create index umag_hacknu_barcode_78ca3f_idx on field(s) barcode, supply_time of model supply
--
CREATE INDEX "umag_hacknu_barcode_78ca3f_idx" ON "umag_hacknu_supply" ("barcode", "supply_time");
--
-- Create index umag_hacknu_barcode_a6066a_idx on field(s) barcode, sale_time of model sale
--
CREATE INDEX "umag_hacknu_barcode_a6066a_idx" ON "umag_hacknu_sale" ("barcode", "sale_time");
COMMIT;

BEGIN;
--
-- Remove index umag_hacknu_barcode_a6066a_idx from sale
--
DROP INDEX IF EXISTS "umag_hacknu_barcode_a6066a_idx";
--
-- Remove index umag_hacknu_barcode_78ca3f_idx from supply
--
DROP INDEX IF EXISTS "umag_hacknu_barcode_78ca3f_idx";
--
-- Add field first_matched_supply to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "first_matched_supply_id" integer NULL CONSTRAINT "umag_hacknu_sale_first_matched_supply_883643fc_fk_umag_hack" REFERENCES "umag_hacknu_supply"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "umag_hacknu_sale_first_matched_supply_883643fc_fk_umag_hack" IMMEDIATE;
--
-- Add field fms_available_quantity to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "fms_available_quantity" integer NULL;
--
-- Add field last_matched_supply to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "last_matched_supply_id" integer NULL CONSTRAINT "umag_hacknu_sale_last_matched_supply__9d158197_fk_umag_hack" REFERENCES "umag_hacknu_supply"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "umag_hacknu_sale_last_matched_supply__9d158197_fk_umag_hack" IMMEDIATE;
--
-- Add field lms_remaining_quantity to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "lms_remaining_quantity" integer NULL;
--
-- Add field total_net_profit to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "total_net_profit" bigint DEFAULT 0 NOT NULL;
ALTER TABLE "umag_hacknu_sale" ALTER COLUMN "total_net_profit" DROP DEFAULT;
--
-- Add field total_quantity to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "total_quantity" bigint DEFAULT 0 NOT NULL;
ALTER TABLE "umag_hacknu_sale" ALTER COLUMN "total_quantity" DROP DEFAULT;
--
-- Add field total_revenue to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "total_revenue" bigint DEFAULT 0 NOT NULL;
ALTER TABLE "umag_hacknu_sale" ALTER COLUMN "total_revenue" DROP DEFAULT;
--
-- Add field first_matched_sale_id to supply
--
ALTER TABLE "umag_hacknu_supply" ADD COLUMN "first_matched_sale_id" integer NULL;
--
-- Create index umag_hacknu_barcode_e72826_idx on field(s) barcode, sale_time, id of model sale
--
CREATE INDEX "umag_hacknu_barcode_e72826_idx" ON "umag_hacknu_sale" ("barcode", "sale_time", "id");
--
-- Create index umag_hacknu_barcode_175df1_idx on field(s) barcode, supply_time, id of model supply
--
CREATE INDEX "umag_hacknu_barcode_175df1_idx" ON "umag_hacknu_supply" ("barcode", "supply_time", "id");
CREATE INDEX "umag_hacknu_sale_first_matched_supply_id_883643fc" ON "umag_hacknu_sale" ("first_matched_supply_id");
CREATE INDEX "umag_hacknu_sale_last_matched_supply_id_9d158197" ON "umag_hacknu_sale" ("last_matched_supply_id");
COMMIT;

BEGIN;
--
-- Remove field first_matched_supply from sale
--
ALTER TABLE "umag_hacknu_sale" DROP COLUMN "first_matched_supply_id" CASCADE;
--
-- Remove field fms_available_quantity from sale
--
ALTER TABLE "umag_hacknu_sale" DROP COLUMN "fms_available_quantity" CASCADE;
--
-- Remove field last_matched_supply from sale
--
ALTER TABLE "umag_hacknu_sale" DROP COLUMN "last_matched_supply_id" CASCADE;
--
-- Remove field lms_remaining_quantity from sale
--
ALTER TABLE "umag_hacknu_sale" DROP COLUMN "lms_remaining_quantity" CASCADE;
--
-- Remove field first_matched_sale_id from supply
--
ALTER TABLE "umag_hacknu_supply" DROP COLUMN "first_matched_sale_id" CASCADE;
COMMIT;

BEGIN;
--
-- Add field last_connected_supply to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "last_connected_supply_id" integer NULL CONSTRAINT "umag_hacknu_sale_last_connected_suppl_90908a85_fk_umag_hack" REFERENCES "umag_hacknu_supply"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "umag_hacknu_sale_last_connected_suppl_90908a85_fk_umag_hack" IMMEDIATE;
--
-- Add field last_connected_supply_remaining_q to sale
--
ALTER TABLE "umag_hacknu_sale" ADD COLUMN "last_connected_supply_remaining_q" integer NULL;
CREATE INDEX "umag_hacknu_sale_last_connected_supply_id_90908a85" ON "umag_hacknu_sale" ("last_connected_supply_id");
COMMIT;
