# Generated by Django 4.2 on 2023-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'umag_hacknu_sale',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('supply_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'umag_hacknu_supply',
            },
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['barcode', 'supply_time'], name='umag_hacknu_barcode_78ca3f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['barcode', 'sale_time'], name='umag_hacknu_barcode_a6066a_idx'),
        ),
    ]
