# Generated by Django 4.2 on 2023-04-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='umag_hacknu_barcode_a6066a_idx',
        ),
        migrations.RemoveIndex(
            model_name='supply',
            name='umag_hacknu_barcode_78ca3f_idx',
        ),
        migrations.AddField(
            model_name='sale',
            name='first_matched_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xx', to='app.supply'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fms_available_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_matched_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='yy', to='app.supply'),
        ),
        migrations.AddField(
            model_name='sale',
            name='lms_remaining_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_net_profit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_revenue',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='first_matched_sale_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['barcode', 'sale_time', 'id'], name='umag_hacknu_barcode_e72826_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['barcode', 'supply_time', 'id'], name='umag_hacknu_barcode_175df1_idx'),
        ),
    ]
