# Generated by Django 4.2 on 2023-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sale_umag_hacknu_barcode_a6066a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_time',
            field=models.DateTimeField(),
        ),
    ]
