# Generated by Django 4.2 on 2023-04-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sale_sale_time_alter_supply_supply_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='first_matched_supply',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='fms_available_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='last_matched_supply',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lms_remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='first_matched_sale_id',
        ),
    ]
