# Generated by Django 4.2 on 2023-04-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sale_first_matched_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='last_connected_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.supply'),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_connected_supply_remaining_q',
            field=models.IntegerField(null=True),
        ),
    ]
